### ISSUE TITLE
Feature Request: Managed Identity authentication examples

### ISSUE THREAD

**Issue by AndrewMcLachlan** [Azure-Samples/MqttApplicationSamples#77]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Feature Request
Are there any plans to include examples of Managed Identity authentication using JWT? I'm trying trying to implement this using MQTTnet and some working examples would really help.

See https://learn.microsoft.com/en-gb/azure/event-grid/mqtt-client-azure-ad-token-and-rbac for reference.

**Comment by rido-min** [comment]
yes, this is work in progress here https://github.com/Azure-Samples/MqttApplicationSamples/tree/feat/jwt/scenarios/jwt_authentication/dotnet/jwt_authentication

**Comment by AndrewMcLachlan** [comment]
Great, thank you, I'll take a look.
